name = "yurisachan-blog-api"
main = "src/index.ts"
compatibility_date = "2026-02-18"
workers_dev = true
routes = [
  { pattern = "api.yurisa.top/*", zone_name = "yurisa.top" },
]

[vars]
CORS_ORIGIN = "https://yurisa.top"

[[d1_databases]]
binding = "DB"
database_name = "blog_d1"
database_id = "2efd44aa-b30c-455f-ad89-679adb22b67f"
migrations_dir = "src/db/migrations"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "7981bfd8885042e9a2961e2061bb1f57"

[observability.logs]
enabled = true
